ALTER TABLE EPROC.EP_NOMORURUT
 DROP PRIMARY KEY CASCADE;

DROP TABLE EPROC.EP_NOMORURUT CASCADE CONSTRAINTS;

CREATE TABLE EPROC.EP_NOMORURUT
(
  KODE_NOMORURUT  VARCHAR2(20 BYTE),
  KODE_KANTOR     VARCHAR2(5 BYTE),
  NOMORURUT       INTEGER
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


ALTER TABLE EPROC.EP_VENDOR_DOKUMEN_REF
 DROP PRIMARY KEY CASCADE;

DROP TABLE EPROC.EP_VENDOR_DOKUMEN_REF CASCADE CONSTRAINTS;

CREATE TABLE EPROC.EP_VENDOR_DOKUMEN_REF
(
  KODE_DOKUMEN_REF  INTEGER,
  NO                VARCHAR2(5 BYTE),
  NAMA              VARCHAR2(255 BYTE),
  TIPE              CHAR(1 BYTE),
  TGL_REKAM         DATE,
  PETUGAS_REKAM     VARCHAR2(10 BYTE),
  TGL_UBAH          DATE,
  PETUGAS_UBAH      VARCHAR2(10 BYTE)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


ALTER TABLE EPROC.EP_VENDOR_STATUS_REGISTRASI
 DROP PRIMARY KEY CASCADE;

DROP TABLE EPROC.EP_VENDOR_STATUS_REGISTRASI CASCADE CONSTRAINTS;

CREATE TABLE EPROC.EP_VENDOR_STATUS_REGISTRASI
(
  KODE_STATUS_REG   INTEGER,
  KODE2_STATUS_REG  VARCHAR2(3 BYTE),
  NAMA_STATUS_REG   VARCHAR2(200 BYTE),
  TGL_REKAM         DATE,
  PETUGAS_REKAM     VARCHAR2(10 BYTE),
  TGL_UBAH          DATE,
  PETUGAS_UBAH      VARCHAR2(10 BYTE)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX EPROC.EP_NOMORURUT_PK ON EPROC.EP_NOMORURUT
(KODE_NOMORURUT, KODE_KANTOR)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX EPROC.EP_VENDOR_DOKUMEN_REF_PK ON EPROC.EP_VENDOR_DOKUMEN_REF
(KODE_DOKUMEN_REF)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX EPROC.EP_VENDOR_SESSION_PK ON EPROC.EP_VENDOR_STATUS_REGISTRASI
(KODE_STATUS_REG)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE EPROC.EP_VENDOR
 DROP PRIMARY KEY CASCADE;

DROP TABLE EPROC.EP_VENDOR CASCADE CONSTRAINTS;

CREATE TABLE EPROC.EP_VENDOR
(
  KODE_VENDOR             INTEGER,
  NAMA_VENDOR             VARCHAR2(50 BYTE),
  KODE_LOGIN              VARCHAR2(50 BYTE),
  PASSWRD                 VARCHAR2(255 BYTE),
  ALAMAT_EMAIL            VARCHAR2(255 BYTE),
  AWALAN                  VARCHAR2(50 BYTE),
  AWALAN_LAIN             VARCHAR2(50 BYTE),
  AKHIRAN                 VARCHAR2(50 BYTE),
  AKHIRAN_LAIN            VARCHAR2(50 BYTE),
  ALAMAT                  VARCHAR2(512 BYTE),
  KOTA                    VARCHAR2(512 BYTE),
  PROPINSI                VARCHAR2(512 BYTE),
  KODE_POS                VARCHAR2(50 BYTE),
  NEGARA                  VARCHAR2(255 BYTE),
  NO_TELP                 VARCHAR2(50 BYTE),
  WEBSITE                 VARCHAR2(512 BYTE),
  NO_DOMISILI             VARCHAR2(50 BYTE),
  TGL_DOMISILI            DATE,
  KADALUARSA_DOMISILI     DATE,
  NAMA_KONTAK             VARCHAR2(255 BYTE),
  JABATAN_KONTAK          VARCHAR2(255 BYTE),
  NO_TELP_KONTAK          VARCHAR2(50 BYTE),
  EMAIL_KONTAK            VARCHAR2(100 BYTE),
  NPP                     VARCHAR2(50 BYTE),
  TGL_NPP                 DATE,
  NO_NPWP                 VARCHAR2(50 BYTE),
  ALAMAT_NPWP             VARCHAR2(255 BYTE),
  KOTA_NPWP               VARCHAR2(100 BYTE),
  PROPINSI_NPWP           VARCHAR2(100 BYTE),
  KODE_POS_NPWP           VARCHAR2(50 BYTE),
  PKP_NPWP                VARCHAR2(50 BYTE),
  NO_PKP_NPWP             VARCHAR2(100 BYTE),
  TIPE_VENDOR             VARCHAR2(100 BYTE),
  TIPE_SIUP_IUJK          VARCHAR2(50 BYTE),
  SIUP_DITERBITKAN_OLEH   VARCHAR2(255 BYTE),
  NO_SIUP                 VARCHAR2(50 BYTE),
  TIPE_SIUP               VARCHAR2(50 BYTE),
  DARI_TGL_SIUP           DATE,
  SAMPAI_TGL_SIUP         DATE,
  TDP_ISSUED_BY           VARCHAR2(255 BYTE),
  NO_TDP                  VARCHAR2(50 BYTE),
  DARI_TGL_TDP            DATE,
  SAMPAI_TGL_TDP          DATE,
  AGEN_PENERBIT           VARCHAR2(255 BYTE),
  DARI_AGEN               DATE,
  HINGGA_AGEN             DATE,
  PENERBIT_IMP            VARCHAR2(255 BYTE),
  DARI_IMP                DATE,
  KE_IMP                  DATE,
  ATT_ORG                 VARCHAR2(50 BYTE),
  MATA_UANG_MODAL_DASAR   VARCHAR2(3 BYTE),
  MODAL_DASAR             NUMBER(19,4),
  MATA_UANG_MODAL_SETOR   VARCHAR2(3 BYTE),
  MODAL_SETOR             NUMBER(19,4),
  MATA_UANG_ASSET_DASAR   VARCHAR2(3 BYTE),
  ASSET_DASAR             NUMBER(19,4),
  MATA_UANG_LAPORAN_KEU   VARCHAR2(3 BYTE),
  TAHUN_LAPORAN_KEU       INTEGER,
  TIPE_LAPORAN_KEU        VARCHAR2(50 BYTE),
  ASSET_LAPORAN_KEU       NUMBER(19,4),
  HUTANG_LAPORAN_KEU      NUMBER(19,4),
  PENDAPATAN_LAPORAN_KEU  NUMBER(19,4),
  LABA_LAPORAN_KEU        NUMBER(19,4),
  GOLONGAN_KEUANGAN       CHAR(1 BYTE),
  BERAKHIR_DARI           DATE,
  BERAKHIR_SAMPAI         DATE,
  DIAKHIRI_OLEH           VARCHAR2(50 BYTE),
  TGL_REKAM               DATE,
  TGL_UBAH                DATE,
  PETUGAS_UBAH            VARCHAR2(50 BYTE),
  STATUS                  VARCHAR2(2 BYTE),
  HALAMAN_SELANJUTNYA     VARCHAR2(255 BYTE),
  KODE_STATUS_REG         INTEGER,
  STATUS_REG              CHAR(1 BYTE),
  SESSION_ID_REG          VARCHAR2(512 BYTE)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


ALTER TABLE EPROC.EP_VENDOR_AGEN
 DROP PRIMARY KEY CASCADE;

DROP TABLE EPROC.EP_VENDOR_AGEN CASCADE CONSTRAINTS;

CREATE TABLE EPROC.EP_VENDOR_AGEN
(
  KODE_VENDOR    INTEGER,
  TIPE           VARCHAR2(50 BYTE),
  PENERBIT       VARCHAR2(250 BYTE),
  TGL_BUAT       DATE,
  TGL_BERAKHIR   DATE,
  NO             VARCHAR2(150 BYTE),
  TGL_REKAM      DATE,
  PETUGAS_REKAM  VARCHAR2(10 BYTE),
  TGL_UBAH       DATE,
  PETUGAS_UBAH   VARCHAR2(10 BYTE)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


ALTER TABLE EPROC.EP_VENDOR_AKTA
 DROP PRIMARY KEY CASCADE;

DROP TABLE EPROC.EP_VENDOR_AKTA CASCADE CONSTRAINTS;

CREATE TABLE EPROC.EP_VENDOR_AKTA
(
  KODE_VENDOR       INTEGER,
  TIPE_AKTA         VARCHAR2(50 BYTE),
  NO_AKTA           VARCHAR2(50 BYTE),
  TGL_PEMBUATAN     DATE,
  NAMA_NOTARIS      VARCHAR2(50 BYTE),
  ALAMAT_NOTARIS    VARCHAR2(255 BYTE),
  PENGESAHAN_HAKIM  DATE,
  BERITA_ACARA_NGR  DATE,
  TGL_REKAM         DATE,
  PETUGAS_REKAM     VARCHAR2(10 BYTE),
  TGL_UBAH          DATE,
  PETUGAS_UBAH      VARCHAR2(10 BYTE)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


ALTER TABLE EPROC.EP_VENDOR_ALAMAT
 DROP PRIMARY KEY CASCADE;

DROP TABLE EPROC.EP_VENDOR_ALAMAT CASCADE CONSTRAINTS;

CREATE TABLE EPROC.EP_VENDOR_ALAMAT
(
  KODE_VENDOR    INTEGER,
  TIPE           VARCHAR2(255 BYTE),
  ALAMAT         VARCHAR2(255 BYTE),
  KOTA           VARCHAR2(50 BYTE),
  NEGARA         VARCHAR2(255 BYTE),
  KODE_POS       VARCHAR2(50 BYTE),
  NO_TELP1       VARCHAR2(50 BYTE),
  NO_TELP2       VARCHAR2(50 BYTE),
  FAX            VARCHAR2(50 BYTE),
  WEBSITE        VARCHAR2(50 BYTE),
  TGL_REKAM      DATE,
  PETUGAS_REKAM  VARCHAR2(10 BYTE),
  TGL_UBAH       DATE,
  PETUGAS_UBAH   VARCHAR2(10 BYTE)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


ALTER TABLE EPROC.EP_VENDOR_BANK
 DROP PRIMARY KEY CASCADE;

DROP TABLE EPROC.EP_VENDOR_BANK CASCADE CONSTRAINTS;

CREATE TABLE EPROC.EP_VENDOR_BANK
(
  KODE_VENDOR    INTEGER,
  NO_REKENING    VARCHAR2(50 BYTE),
  NAMA_REKENING  VARCHAR2(255 BYTE),
  NAMA_BANK      VARCHAR2(50 BYTE),
  CABANG         VARCHAR2(50 BYTE),
  MATA_UANG      VARCHAR2(50 BYTE),
  ALAMAT         VARCHAR2(255 BYTE),
  TGL_REKAM      DATE,
  PETUGAS_REKAM  VARCHAR2(10 BYTE),
  TGL_UBAH       DATE,
  PETUGAS_UBAH   VARCHAR2(10 BYTE)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


ALTER TABLE EPROC.EP_VENDOR_BARANG
 DROP PRIMARY KEY CASCADE;

DROP TABLE EPROC.EP_VENDOR_BARANG CASCADE CONSTRAINTS;

CREATE TABLE EPROC.EP_VENDOR_BARANG
(
  KODE_VENDOR    INTEGER,
  NAMA_BARANG    VARCHAR2(255 BYTE),
  KODE_BARANG    VARCHAR2(50 BYTE),
  KETERANGAN     VARCHAR2(1024 BYTE),
  MEREK          VARCHAR2(50 BYTE),
  SUMBER         VARCHAR2(50 BYTE),
  TIPE           VARCHAR2(50 BYTE),
  TERDAFTAR      CHAR(1 BYTE),
  TGL_REKAM      DATE,
  PETUGAS_REKAM  VARCHAR2(10 BYTE),
  TGL_UBAH       DATE,
  PETUGAS_UBAH   VARCHAR2(10 BYTE)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


ALTER TABLE EPROC.EP_VENDOR_DEWAN_DIREKSI
 DROP PRIMARY KEY CASCADE;

DROP TABLE EPROC.EP_VENDOR_DEWAN_DIREKSI CASCADE CONSTRAINTS;

CREATE TABLE EPROC.EP_VENDOR_DEWAN_DIREKSI
(
  KODE_VENDOR    INTEGER,
  TIPE           VARCHAR2(50 BYTE),
  NAMA           VARCHAR2(512 BYTE),
  JABATAN        VARCHAR2(255 BYTE),
  NO_TELP        VARCHAR2(50 BYTE),
  EMAIL          VARCHAR2(255 BYTE),
  NO_KTP         VARCHAR2(255 BYTE),
  NO_NPWP        VARCHAR2(255 BYTE),
  TGL_REKAM      DATE,
  PETUGAS_REKAM  VARCHAR2(10 BYTE),
  TGL_UBAH       DATE,
  PETUGAS_UBAH   VARCHAR2(10 BYTE)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


ALTER TABLE EPROC.EP_VENDOR_DOKUMEN
 DROP PRIMARY KEY CASCADE;

DROP TABLE EPROC.EP_VENDOR_DOKUMEN CASCADE CONSTRAINTS;

CREATE TABLE EPROC.EP_VENDOR_DOKUMEN
(
  KODE_VENDOR       INTEGER,
  KODE_DOKUMEN_REF  INTEGER,
  STATUS            CHAR(1 BYTE),
  NOTE              VARCHAR2(4000 BYTE),
  KETERANGAN        VARCHAR2(4000 BYTE),
  TGL_REKAM         DATE,
  PETUGAS_REKAM     VARCHAR2(10 BYTE),
  TGL_UBAH          DATE,
  PETUGAS_UBAH      VARCHAR2(10 BYTE)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


ALTER TABLE EPROC.EP_VENDOR_DOKUMEN_PENDUKUNG
 DROP PRIMARY KEY CASCADE;

DROP TABLE EPROC.EP_VENDOR_DOKUMEN_PENDUKUNG CASCADE CONSTRAINTS;

CREATE TABLE EPROC.EP_VENDOR_DOKUMEN_PENDUKUNG
(
  KODE_VENDOR         INTEGER,
  KETERANGAN_DOKUMEN  VARCHAR2(100 BYTE),
  URL_DOKUMEN         VARCHAR2(1024 BYTE),
  NAMA_FILE           VARCHAR2(100 BYTE),
  TGL_REKAM           DATE,
  PETUGAS_REKAM       VARCHAR2(10 BYTE),
  TGL_UBAH            DATE,
  PETUGAS_UBAH        VARCHAR2(10 BYTE)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


ALTER TABLE EPROC.EP_VENDOR_IJIN
 DROP PRIMARY KEY CASCADE;

DROP TABLE EPROC.EP_VENDOR_IJIN CASCADE CONSTRAINTS;

CREATE TABLE EPROC.EP_VENDOR_IJIN
(
  KODE_VENDOR    INTEGER,
  TIPE           VARCHAR2(50 BYTE),
  PENERBIT       VARCHAR2(250 BYTE),
  NO             VARCHAR2(50 BYTE),
  TGL_MULAI      DATE,
  TGL_BERAKHIR   DATE,
  TGL_REKAM      DATE,
  PETUGAS_REKAM  VARCHAR2(10 BYTE),
  TGL_UBAH       DATE,
  PETUGAS_UBAH   VARCHAR2(10 BYTE)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


ALTER TABLE EPROC.EP_VENDOR_INFORMASI_LAIN
 DROP PRIMARY KEY CASCADE;

DROP TABLE EPROC.EP_VENDOR_INFORMASI_LAIN CASCADE CONSTRAINTS;

CREATE TABLE EPROC.EP_VENDOR_INFORMASI_LAIN
(
  KODE_VENDOR    INTEGER,
  TIPE           VARCHAR2(100 BYTE),
  NAMA           VARCHAR2(255 BYTE),
  ALAMAT         VARCHAR2(255 BYTE),
  KOTA           VARCHAR2(50 BYTE),
  NEGARA         VARCHAR2(50 BYTE),
  KODE_POS       VARCHAR2(50 BYTE),
  KUALIFIKASI    VARCHAR2(1024 BYTE),
  HUBUNGAN       VARCHAR2(255 BYTE),
  TGL_REKAM      DATE,
  PETUGAS_REKAM  VARCHAR2(10 BYTE),
  TGL_UBAH       DATE,
  PETUGAS_UBAH   VARCHAR2(10 BYTE)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


ALTER TABLE EPROC.EP_VENDOR_JASA
 DROP PRIMARY KEY CASCADE;

DROP TABLE EPROC.EP_VENDOR_JASA CASCADE CONSTRAINTS;

CREATE TABLE EPROC.EP_VENDOR_JASA
(
  KODE_VENDOR    INTEGER,
  KODE_JASA      VARCHAR2(50 BYTE),
  NAMA_JASA      VARCHAR2(255 BYTE),
  TIPE           VARCHAR2(50 BYTE),
  TERDAFTAR      CHAR(1 BYTE),
  TGL_REKAM      DATE,
  PETUGAS_REKAM  VARCHAR2(10 BYTE),
  TGL_UBAH       DATE,
  PETUGAS_UBAH   VARCHAR2(10 BYTE)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


ALTER TABLE EPROC.EP_VENDOR_KINERJA
 DROP PRIMARY KEY CASCADE;

DROP TABLE EPROC.EP_VENDOR_KINERJA CASCADE CONSTRAINTS;

CREATE TABLE EPROC.EP_VENDOR_KINERJA
(
  KODE_VENDOR           INTEGER,
  TANGGAL               DATE,
  KODE_TENDER           VARCHAR2(10 BYTE),
  TIPE_KOMODITI         CHAR(1 BYTE),
  KODE_KEL_JASA_BARANG  VARCHAR2(20 BYTE),
  KODE_PARAM            VARCHAR2(50 BYTE),
  NAMA_PARAM            VARCHAR2(255 BYTE),
  PILIHAN_PARAM         INTEGER,
  TGL_REKAM             DATE,
  PETUGAS_REKAM         VARCHAR2(10 BYTE),
  TGL_UBAH              DATE,
  PETUGAS_UBAH          VARCHAR2(10 BYTE)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


ALTER TABLE EPROC.EP_VENDOR_KOMENTAR
 DROP PRIMARY KEY CASCADE;

DROP TABLE EPROC.EP_VENDOR_KOMENTAR CASCADE CONSTRAINTS;

CREATE TABLE EPROC.EP_VENDOR_KOMENTAR
(
  KODE_KOMENTAR  INTEGER,
  KODE_VENDOR    INTEGER,
  NAMA_KOMENTAR  VARCHAR2(50 BYTE),
  STATUS         VARCHAR2(10 BYTE),
  NAMA_VENDOR    VARCHAR2(500 BYTE),
  TGL_BUAT       DATE,
  TGL_SELESAI    DATE,
  URL            VARCHAR2(200 BYTE),
  TGL_REKAM      DATE,
  PETUGAS_REKAM  VARCHAR2(10 BYTE),
  TGL_UBAH       DATE,
  PETUGAS_UBAH   VARCHAR2(10 BYTE)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


ALTER TABLE EPROC.EP_VENDOR_LAPORAN_KEUANGAN
 DROP PRIMARY KEY CASCADE;

DROP TABLE EPROC.EP_VENDOR_LAPORAN_KEUANGAN CASCADE CONSTRAINTS;

CREATE TABLE EPROC.EP_VENDOR_LAPORAN_KEUANGAN
(
  KODE_VENDOR    INTEGER,
  MATA_UANG      VARCHAR2(3 BYTE),
  TAHUN          INTEGER,
  TIPE           VARCHAR2(50 BYTE),
  NILAI_ASSET    NUMBER(19,4),
  HUTANG         NUMBER(19,4),
  PENDAPATAN     NUMBER(19,4),
  LABA_BERSIH    NUMBER(19,4),
  KELAS          CHAR(1 BYTE),
  TGL_REKAM      DATE,
  PETUGAS_REKAM  VARCHAR2(10 BYTE),
  TGL_UBAH       DATE,
  PETUGAS_UBAH   VARCHAR2(10 BYTE)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


ALTER TABLE EPROC.EP_VENDOR_PERALATAN
 DROP PRIMARY KEY CASCADE;

DROP TABLE EPROC.EP_VENDOR_PERALATAN CASCADE CONSTRAINTS;

CREATE TABLE EPROC.EP_VENDOR_PERALATAN
(
  KODE_VENDOR      INTEGER,
  KATEGORI         VARCHAR2(50 BYTE),
  NAMA_PERALATAN   VARCHAR2(255 BYTE),
  SPESIFIKASI      VARCHAR2(512 BYTE),
  TAHUN_PEMBUATAN  INTEGER,
  JUMLAH           NUMBER(18),
  TGL_REKAM        DATE,
  PETUGAS_REKAM    VARCHAR2(10 BYTE),
  TGL_UBAH         DATE,
  PETUGAS_UBAH     VARCHAR2(10 BYTE)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


ALTER TABLE EPROC.EP_VENDOR_SERTIFIKAT
 DROP PRIMARY KEY CASCADE;

DROP TABLE EPROC.EP_VENDOR_SERTIFIKAT CASCADE CONSTRAINTS;

CREATE TABLE EPROC.EP_VENDOR_SERTIFIKAT
(
  KODE_VENDOR     INTEGER,
  NAMA            VARCHAR2(255 BYTE),
  PENERBIT        VARCHAR2(255 BYTE),
  TIPE            VARCHAR2(50 BYTE),
  TIPE_LAIN       VARCHAR2(50 BYTE),
  BERLAKU_DARI    DATE,
  BERLAKU_HINGGA  DATE,
  NO_SERTIFIKAT   VARCHAR2(50 BYTE),
  TGL_REKAM       DATE,
  PETUGAS_REKAM   VARCHAR2(10 BYTE),
  TGL_UBAH        DATE,
  PETUGAS_UBAH    VARCHAR2(10 BYTE)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


ALTER TABLE EPROC.EP_VENDOR_TENAGA_KERJA
 DROP PRIMARY KEY CASCADE;

DROP TABLE EPROC.EP_VENDOR_TENAGA_KERJA CASCADE CONSTRAINTS;

CREATE TABLE EPROC.EP_VENDOR_TENAGA_KERJA
(
  KODE_VENDOR          INTEGER,
  NAMA                 VARCHAR2(255 BYTE),
  TIPE                 VARCHAR2(50 BYTE),
  PENDIDIKAN_TERAKHIR  VARCHAR2(50 BYTE),
  KEAHLIAN             VARCHAR2(1024 BYTE),
  TAHUN_BERAKHIR       INTEGER,
  STATUS_PEGAWAI       VARCHAR2(50 BYTE),
  TIPE_PEGAWAI         VARCHAR2(50 BYTE),
  TGL_REKAM            DATE,
  PETUGAS_REKAM        VARCHAR2(10 BYTE),
  TGL_UBAH             DATE,
  PETUGAS_UBAH         VARCHAR2(10 BYTE)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


ALTER TABLE EPROC.EP_VENDOR_TIPE
 DROP PRIMARY KEY CASCADE;

DROP TABLE EPROC.EP_VENDOR_TIPE CASCADE CONSTRAINTS;

CREATE TABLE EPROC.EP_VENDOR_TIPE
(
  KODE_VENDOR    INTEGER,
  TIPE_VENDOR    VARCHAR2(255 BYTE),
  TGL_REKAM      DATE,
  PETUGAS_REKAM  VARCHAR2(10 BYTE),
  TGL_UBAH       DATE,
  PETUGAS_UBAH   VARCHAR2(10 BYTE)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX EPROC.EP_VENDOR_AGEN_PK ON EPROC.EP_VENDOR_AGEN
(NO, TIPE, KODE_VENDOR)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX EPROC.EP_VENDOR_AKTA_PK ON EPROC.EP_VENDOR_AKTA
(KODE_VENDOR, TIPE_AKTA)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX EPROC.EP_VENDOR_ALAMAT_PK ON EPROC.EP_VENDOR_ALAMAT
(KODE_VENDOR, TIPE)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX EPROC.EP_VENDOR_BANK_PK ON EPROC.EP_VENDOR_BANK
(KODE_VENDOR, NO_REKENING)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX EPROC.EP_VENDOR_BARANG_PK ON EPROC.EP_VENDOR_BARANG
(KODE_VENDOR, NAMA_BARANG)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX EPROC.EP_VENDOR_DEWAN_DIREKSI_PK ON EPROC.EP_VENDOR_DEWAN_DIREKSI
(JABATAN, NAMA, TIPE, KODE_VENDOR)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX EPROC.EP_VENDOR_DOKUMEN_PENDUKUNG_PK ON EPROC.EP_VENDOR_DOKUMEN_PENDUKUNG
(KODE_VENDOR, KETERANGAN_DOKUMEN)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX EPROC.EP_VENDOR_DOKUMEN_PK ON EPROC.EP_VENDOR_DOKUMEN
(KODE_VENDOR, KODE_DOKUMEN_REF)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX EPROC.EP_VENDOR_IJIN_PK ON EPROC.EP_VENDOR_IJIN
(KODE_VENDOR, TIPE)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX EPROC.EP_VENDOR_INFORMASI_LAIN_PK ON EPROC.EP_VENDOR_INFORMASI_LAIN
(KODE_VENDOR, TIPE)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX EPROC.EP_VENDOR_JASA_PK ON EPROC.EP_VENDOR_JASA
(KODE_VENDOR, KODE_JASA)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX EPROC.EP_VENDOR_KINERJA_PK ON EPROC.EP_VENDOR_KINERJA
(KODE_VENDOR, KODE_TENDER)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX EPROC.EP_VENDOR_KOMENTAR_PK ON EPROC.EP_VENDOR_KOMENTAR
(KODE_KOMENTAR, KODE_VENDOR)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX EPROC.EP_VENDOR_LAPORAN_KEUANGAN_PK ON EPROC.EP_VENDOR_LAPORAN_KEUANGAN
(KODE_VENDOR, MATA_UANG, TAHUN, TIPE)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX EPROC.EP_VENDOR_PERALATAN_PK ON EPROC.EP_VENDOR_PERALATAN
(KODE_VENDOR, NAMA_PERALATAN)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX EPROC.EP_VENDOR_PK ON EPROC.EP_VENDOR
(KODE_VENDOR)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX EPROC.EP_VENDOR_SERTIFIKAT_PK ON EPROC.EP_VENDOR_SERTIFIKAT
(KODE_VENDOR, NAMA)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX EPROC.EP_VENDOR_TENAGA_KERJA_PK ON EPROC.EP_VENDOR_TENAGA_KERJA
(KODE_VENDOR, NAMA)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX EPROC.EP_VENDOR_TIPE_PK ON EPROC.EP_VENDOR_TIPE
(KODE_VENDOR, TIPE_VENDOR)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE EPROC.EP_NOMORURUT ADD (
  CONSTRAINT EP_NOMORURUT_PK
  PRIMARY KEY
  (KODE_NOMORURUT, KODE_KANTOR)
  USING INDEX EPROC.EP_NOMORURUT_PK
  ENABLE VALIDATE);

ALTER TABLE EPROC.EP_VENDOR_DOKUMEN_REF ADD (
  CONSTRAINT EP_VENDOR_DOKUMEN_REF_PK
  PRIMARY KEY
  (KODE_DOKUMEN_REF)
  USING INDEX EPROC.EP_VENDOR_DOKUMEN_REF_PK
  ENABLE VALIDATE);

ALTER TABLE EPROC.EP_VENDOR_STATUS_REGISTRASI ADD (
  CONSTRAINT EP_VENDOR_SESSION_PK
  PRIMARY KEY
  (KODE_STATUS_REG)
  USING INDEX EPROC.EP_VENDOR_SESSION_PK
  ENABLE VALIDATE);

ALTER TABLE EPROC.EP_VENDOR ADD (
  CONSTRAINT EP_VENDOR_PK
  PRIMARY KEY
  (KODE_VENDOR)
  USING INDEX EPROC.EP_VENDOR_PK
  ENABLE VALIDATE);

ALTER TABLE EPROC.EP_VENDOR_AGEN ADD (
  CONSTRAINT EP_VENDOR_AGEN_PK
  PRIMARY KEY
  (NO, TIPE, KODE_VENDOR)
  USING INDEX EPROC.EP_VENDOR_AGEN_PK
  ENABLE VALIDATE);

ALTER TABLE EPROC.EP_VENDOR_AKTA ADD (
  CONSTRAINT EP_VENDOR_AKTA_PK
  PRIMARY KEY
  (KODE_VENDOR, TIPE_AKTA)
  USING INDEX EPROC.EP_VENDOR_AKTA_PK
  ENABLE VALIDATE);

ALTER TABLE EPROC.EP_VENDOR_ALAMAT ADD (
  CONSTRAINT EP_VENDOR_ALAMAT_PK
  PRIMARY KEY
  (KODE_VENDOR, TIPE)
  USING INDEX EPROC.EP_VENDOR_ALAMAT_PK
  ENABLE VALIDATE);

ALTER TABLE EPROC.EP_VENDOR_BANK ADD (
  CONSTRAINT EP_VENDOR_BANK_PK
  PRIMARY KEY
  (KODE_VENDOR, NO_REKENING)
  USING INDEX EPROC.EP_VENDOR_BANK_PK
  ENABLE VALIDATE);

ALTER TABLE EPROC.EP_VENDOR_BARANG ADD (
  CONSTRAINT EP_VENDOR_BARANG_PK
  PRIMARY KEY
  (KODE_VENDOR, NAMA_BARANG)
  USING INDEX EPROC.EP_VENDOR_BARANG_PK
  ENABLE VALIDATE);

ALTER TABLE EPROC.EP_VENDOR_DEWAN_DIREKSI ADD (
  CONSTRAINT EP_VENDOR_DEWAN_DIREKSI_PK
  PRIMARY KEY
  (JABATAN, NAMA, TIPE, KODE_VENDOR)
  USING INDEX EPROC.EP_VENDOR_DEWAN_DIREKSI_PK
  ENABLE VALIDATE);

ALTER TABLE EPROC.EP_VENDOR_DOKUMEN ADD (
  CONSTRAINT EP_VENDOR_DOKUMEN_PK
  PRIMARY KEY
  (KODE_VENDOR, KODE_DOKUMEN_REF)
  USING INDEX EPROC.EP_VENDOR_DOKUMEN_PK
  ENABLE VALIDATE);

ALTER TABLE EPROC.EP_VENDOR_DOKUMEN_PENDUKUNG ADD (
  CONSTRAINT EP_VENDOR_DOKUMEN_PENDUKUNG_PK
  PRIMARY KEY
  (KODE_VENDOR, KETERANGAN_DOKUMEN)
  USING INDEX EPROC.EP_VENDOR_DOKUMEN_PENDUKUNG_PK
  ENABLE VALIDATE);

ALTER TABLE EPROC.EP_VENDOR_IJIN ADD (
  CONSTRAINT EP_VENDOR_IJIN_PK
  PRIMARY KEY
  (KODE_VENDOR, TIPE)
  USING INDEX EPROC.EP_VENDOR_IJIN_PK
  ENABLE VALIDATE);

ALTER TABLE EPROC.EP_VENDOR_INFORMASI_LAIN ADD (
  CONSTRAINT EP_VENDOR_INFORMASI_LAIN_PK
  PRIMARY KEY
  (KODE_VENDOR, TIPE)
  USING INDEX EPROC.EP_VENDOR_INFORMASI_LAIN_PK
  ENABLE VALIDATE);

ALTER TABLE EPROC.EP_VENDOR_JASA ADD (
  CONSTRAINT EP_VENDOR_JASA_PK
  PRIMARY KEY
  (KODE_VENDOR, KODE_JASA)
  USING INDEX EPROC.EP_VENDOR_JASA_PK
  ENABLE VALIDATE);

ALTER TABLE EPROC.EP_VENDOR_KINERJA ADD (
  CONSTRAINT EP_VENDOR_KINERJA_PK
  PRIMARY KEY
  (KODE_VENDOR, KODE_TENDER)
  USING INDEX EPROC.EP_VENDOR_KINERJA_PK
  ENABLE VALIDATE);

ALTER TABLE EPROC.EP_VENDOR_KOMENTAR ADD (
  CONSTRAINT EP_VENDOR_KOMENTAR_PK
  PRIMARY KEY
  (KODE_KOMENTAR, KODE_VENDOR)
  USING INDEX EPROC.EP_VENDOR_KOMENTAR_PK
  ENABLE VALIDATE);

ALTER TABLE EPROC.EP_VENDOR_LAPORAN_KEUANGAN ADD (
  CONSTRAINT EP_VENDOR_LAPORAN_KEUANGAN_PK
  PRIMARY KEY
  (KODE_VENDOR, MATA_UANG, TAHUN, TIPE)
  USING INDEX EPROC.EP_VENDOR_LAPORAN_KEUANGAN_PK
  ENABLE VALIDATE);

ALTER TABLE EPROC.EP_VENDOR_PERALATAN ADD (
  CONSTRAINT EP_VENDOR_PERALATAN_PK
  PRIMARY KEY
  (KODE_VENDOR, NAMA_PERALATAN)
  USING INDEX EPROC.EP_VENDOR_PERALATAN_PK
  ENABLE VALIDATE);

ALTER TABLE EPROC.EP_VENDOR_SERTIFIKAT ADD (
  CONSTRAINT EP_VENDOR_SERTIFIKAT_PK
  PRIMARY KEY
  (KODE_VENDOR, NAMA)
  USING INDEX EPROC.EP_VENDOR_SERTIFIKAT_PK
  ENABLE VALIDATE);

ALTER TABLE EPROC.EP_VENDOR_TENAGA_KERJA ADD (
  CONSTRAINT EP_VENDOR_TENAGA_KERJA_PK
  PRIMARY KEY
  (KODE_VENDOR, NAMA)
  USING INDEX EPROC.EP_VENDOR_TENAGA_KERJA_PK
  ENABLE VALIDATE);

ALTER TABLE EPROC.EP_VENDOR_TIPE ADD (
  CONSTRAINT EP_VENDOR_TIPE_PK
  PRIMARY KEY
  (KODE_VENDOR, TIPE_VENDOR)
  USING INDEX EPROC.EP_VENDOR_TIPE_PK
  ENABLE VALIDATE);

ALTER TABLE EPROC.EP_VENDOR ADD (
  CONSTRAINT EP_VENDOR_FK 
  FOREIGN KEY (KODE_STATUS_REG) 
  REFERENCES EPROC.EP_VENDOR_STATUS_REGISTRASI (KODE_STATUS_REG)
  ENABLE VALIDATE);

ALTER TABLE EPROC.EP_VENDOR_AGEN ADD (
  CONSTRAINT EP_VENDOR_AGEN_FK 
  FOREIGN KEY (KODE_VENDOR) 
  REFERENCES EPROC.EP_VENDOR (KODE_VENDOR)
  ENABLE VALIDATE);

ALTER TABLE EPROC.EP_VENDOR_AKTA ADD (
  CONSTRAINT EP_VENDOR_AKTA_FK 
  FOREIGN KEY (KODE_VENDOR) 
  REFERENCES EPROC.EP_VENDOR (KODE_VENDOR)
  ENABLE VALIDATE);

ALTER TABLE EPROC.EP_VENDOR_ALAMAT ADD (
  CONSTRAINT EP_VENDOR_ALAMAT_FK 
  FOREIGN KEY (KODE_VENDOR) 
  REFERENCES EPROC.EP_VENDOR (KODE_VENDOR)
  ENABLE VALIDATE);

ALTER TABLE EPROC.EP_VENDOR_BANK ADD (
  CONSTRAINT EP_VENDOR_BANK_FK 
  FOREIGN KEY (KODE_VENDOR) 
  REFERENCES EPROC.EP_VENDOR (KODE_VENDOR)
  ENABLE VALIDATE);

ALTER TABLE EPROC.EP_VENDOR_BARANG ADD (
  CONSTRAINT EP_VENDOR_BARANG_FK 
  FOREIGN KEY (KODE_VENDOR) 
  REFERENCES EPROC.EP_VENDOR (KODE_VENDOR)
  ENABLE VALIDATE);

ALTER TABLE EPROC.EP_VENDOR_DEWAN_DIREKSI ADD (
  CONSTRAINT EP_VENDOR_DEWAN_DIREKSI_FK 
  FOREIGN KEY (KODE_VENDOR) 
  REFERENCES EPROC.EP_VENDOR (KODE_VENDOR)
  ENABLE VALIDATE);

ALTER TABLE EPROC.EP_VENDOR_DOKUMEN ADD (
  CONSTRAINT EP_VENDOR_DOKUMEN_FK 
  FOREIGN KEY (KODE_VENDOR) 
  REFERENCES EPROC.EP_VENDOR (KODE_VENDOR)
  ENABLE VALIDATE,
  CONSTRAINT EP_VENDOR_DOKUMEN_FK2 
  FOREIGN KEY (KODE_DOKUMEN_REF) 
  REFERENCES EPROC.EP_VENDOR_DOKUMEN_REF (KODE_DOKUMEN_REF)
  ENABLE VALIDATE);

ALTER TABLE EPROC.EP_VENDOR_DOKUMEN_PENDUKUNG ADD (
  CONSTRAINT EP_VENDOR_DOKUMEN_PENDUKUNG_FK 
  FOREIGN KEY (KODE_VENDOR) 
  REFERENCES EPROC.EP_VENDOR (KODE_VENDOR)
  ENABLE VALIDATE);

ALTER TABLE EPROC.EP_VENDOR_IJIN ADD (
  CONSTRAINT EP_VENDOR_IJIN_FK 
  FOREIGN KEY (KODE_VENDOR) 
  REFERENCES EPROC.EP_VENDOR (KODE_VENDOR)
  ENABLE VALIDATE);

ALTER TABLE EPROC.EP_VENDOR_INFORMASI_LAIN ADD (
  CONSTRAINT EP_VENDOR_INFORMASI_LAIN_FK 
  FOREIGN KEY (KODE_VENDOR) 
  REFERENCES EPROC.EP_VENDOR (KODE_VENDOR)
  ENABLE VALIDATE);

ALTER TABLE EPROC.EP_VENDOR_JASA ADD (
  CONSTRAINT EP_VENDOR_JASA_FK 
  FOREIGN KEY (KODE_VENDOR) 
  REFERENCES EPROC.EP_VENDOR (KODE_VENDOR)
  ENABLE VALIDATE);

ALTER TABLE EPROC.EP_VENDOR_KINERJA ADD (
  CONSTRAINT EP_VENDOR_KINERJA_FK 
  FOREIGN KEY (KODE_VENDOR) 
  REFERENCES EPROC.EP_VENDOR (KODE_VENDOR)
  ENABLE VALIDATE);

ALTER TABLE EPROC.EP_VENDOR_KOMENTAR ADD (
  CONSTRAINT EP_VENDOR_KOMENTAR_FK 
  FOREIGN KEY (KODE_VENDOR) 
  REFERENCES EPROC.EP_VENDOR (KODE_VENDOR)
  ENABLE VALIDATE);

ALTER TABLE EPROC.EP_VENDOR_LAPORAN_KEUANGAN ADD (
  CONSTRAINT EP_VENDOR_LAPORAN_KEUANGAN_FK 
  FOREIGN KEY (KODE_VENDOR) 
  REFERENCES EPROC.EP_VENDOR (KODE_VENDOR)
  ENABLE VALIDATE);

ALTER TABLE EPROC.EP_VENDOR_PERALATAN ADD (
  CONSTRAINT EP_VENDOR_PERALATAN_FK 
  FOREIGN KEY (KODE_VENDOR) 
  REFERENCES EPROC.EP_VENDOR (KODE_VENDOR)
  ENABLE VALIDATE);

ALTER TABLE EPROC.EP_VENDOR_SERTIFIKAT ADD (
  CONSTRAINT EP_VENDOR_SERTIFIKAT_FK 
  FOREIGN KEY (KODE_VENDOR) 
  REFERENCES EPROC.EP_VENDOR (KODE_VENDOR)
  ENABLE VALIDATE);

ALTER TABLE EPROC.EP_VENDOR_TENAGA_KERJA ADD (
  CONSTRAINT EP_VENDOR_TENAGA_KERJA_FK 
  FOREIGN KEY (KODE_VENDOR) 
  REFERENCES EPROC.EP_VENDOR (KODE_VENDOR)
  ENABLE VALIDATE);

ALTER TABLE EPROC.EP_VENDOR_TIPE ADD (
  CONSTRAINT EP_VENDOR_TIPE_FK 
  FOREIGN KEY (KODE_VENDOR) 
  REFERENCES EPROC.EP_VENDOR (KODE_VENDOR)
  ENABLE VALIDATE);
